### ISSUE TITLE
[機改]Reward, Bank gift,...やその他のコマンド。

### ISSUE THREAD

**Issue by t0206** [peyang-Celeron/AreaPvPit#12]
Adminの場合 /reward <Player> でGUIが開き自分の持ってる持ってない関係なしに送れる。
一般なら/gift <Player>でGUIが開き選んでアイテムの送信ができる(自分のゴールドからその分引かれる)(ゴールドも送れる)
あと銀行機能みたいなのも欲しい
/bank で自分のゴールドを預けたり引き落としたりできる。

Lynx(例のあれ)と互換性のあるreport機能(これはあったらいいなという欲望なので上のbankとかrewardとかgiftがメインのIssueです！)
/report <Player> <reason>や
/tempban <player> <time> <reason>....

report受けたらstaffには
[ADMIN]Fishy: Report of PLAYER fly  speed nofall scaffold....のようにでる。

お願いします。。。！

**Comment by PeyaPeyaPeyang** [comment]
/reportや/tempban等の機能は、原作にも登場していませんし、Pitを作成するプラグインなので見送りいたします。
/bankについては、アイテム化しても需要がないと考えられますが、コメントお願いいたします。

**Comment by t0206** [comment]
bankは自分のゴールドを預けれるみたいな(？)まぁ本作にはないけど（（（（（

**Comment by PeyaPeyaPeyang** [comment]
預ける必要がないと思われるので実装は見送ります。

**Comment by PeyaPeyaPeyang** [comment]
giftに関しては、Goldを送金する際、そのプレイヤーが破産してしまう可能性があるため、実装を見送ります
